curl --request GET \
  --url http://localhost:9960/users/ \
  --header 'authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2Rldi13c3BqeGk1ZjZtanFzamVhLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJxWlVMVDhNc2htNFBaV2I2RUtxblYwY2xwOGRVV0xEZEBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9hcGkucG9rZW1vbmRyYWZ0em9uZS5jb20iLCJpYXQiOjE3MDY5NzYzNzIsImV4cCI6MTcwNzA2Mjc3MiwiYXpwIjoicVpVTFQ4TXNobTRQWldiNkVLcW5WMGNscDhkVVdMRGQiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.2RP1--JVNibyvPYkw_oRJRL5DmBsUSb2jo4cLhnP-Mo'