curl --request GET \
  --url http://localhost:9960/draft/lumaris/teams \
  --header 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjlrNWhMTHJydHpzQmlveTYwU3V5byJ9.eyJpc3MiOiJodHRwczovL2Rldi13c3BqeGk1ZjZtanFzamVhLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDExMDIxNjQ0MjE0MzEyOTUyMTA2NiIsImF1ZCI6WyJodHRwczovL2Rldi13c3BqeGk1ZjZtanFzamVhLnVzLmF1dGgwLmNvbS9hcGkvdjIvIiwiaHR0cHM6Ly9kZXYtd3NwanhpNWY2bWpxc2plYS51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzA3MDYyOTE1LCJleHAiOjE3MDcxNDkzMTUsImF6cCI6Im5BeXZIU09MMVBic0ZaZm9kemdJalJnWUJVQTFNMURIIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCJ9.MXpaSgQ-0careQ2ZmfCVXH6-npzZlJQ01O_w8szC2xWxYT5s3w0sEO59dXswoTzVSLm2KcqxYts3Xf9XNqv5sj9kKsNfoGucApQMfvm7tZz3AJ3QuAmBHEQFbh3aHiC5w-ujK1q0p_sLhlQrqYbO1uN5QsyPen_xRTYhXwMw5uCGvLJD_aOpLnp9lcKpmZC_jLvyx_lP7YoOPgZZiPn2cMVbTjlPiY8BbDIyqL_Qq_VanZig40sGwBjj3UkF_uVncbXqL7fIFRGDljVOejm4icvMFyZzlaRHunreE8o8Yz4hMLFGsf6lmMj5Uj8idd8Dz75Y017OwoCDQhIbddJ6pA'